export const CAPABILITIES = {
  MANAGE_SCHOOL: "SCHOOL.MANAGE",
  VIEW_STUDENTS: "STUDENTS.VIEW",
  MANAGE_STUDENTS: "STUDENTS.MANAGE",
  RECORD_ATTENDANCE: "ATTENDANCE.RECORD",
  VIEW_ATTENDANCE: "ATTENDANCE.VIEW",
  CREATE_ASSESSMENT: "ASSESSMENT.CREATE",
  SUBMIT_RESULTS: "RESULT.SUBMIT",
  APPROVE_RESULTS: "RESULT.APPROVE",
  VIEW_FINANCE: "FINANCE.VIEW",
  MANAGE_FINANCE: "FINANCE.MANAGE",
} as const;

export type CapabilityCode = (typeof CAPABILITIES)[keyof typeof CAPABILITIES];
